services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"

  auth:
    build: ./auth-service
    container_name: auth_service
    restart: always
    volumes:
      - ./auth-service:/app
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  blog:
    build: ./blog-service
    container_name: blog_service
    restart: always
    volumes:
      - ./blog-service/app:/app
    env_file:
      - ./blog-service/.env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: